// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHSjxEfuNPkniS2sT9IE4Vcew5WUu2tqY',
    appId: '1:298093404093:web:533b9a9cb9626773cdbcd4',
    messagingSenderId: '298093404093',
    projectId: 'ifebuche-project',
    authDomain: 'ifebuche-project.firebaseapp.com',
    storageBucket: 'ifebuche-project.appspot.com',
    measurementId: 'G-L194V3EG09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdL2Se0ma-Ficzn-Uo0EaBbXkil4CN_hw',
    appId: '1:298093404093:android:c9ad4688f873156dcdbcd4',
    messagingSenderId: '298093404093',
    projectId: 'ifebuche-project',
    storageBucket: 'ifebuche-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApuEzh6TLnycxExcDXx_Xs3fObizEkLTQ',
    appId: '1:298093404093:ios:ac7dad82952b750ccdbcd4',
    messagingSenderId: '298093404093',
    projectId: 'ifebuche-project',
    storageBucket: 'ifebuche-project.appspot.com',
    iosClientId: '298093404093-ngk0ua3lj7jt6igg8vifjbisgqem026f.apps.googleusercontent.com',
    iosBundleId: 'ife.com.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApuEzh6TLnycxExcDXx_Xs3fObizEkLTQ',
    appId: '1:298093404093:ios:20bad961508e5f36cdbcd4',
    messagingSenderId: '298093404093',
    projectId: 'ifebuche-project',
    storageBucket: 'ifebuche-project.appspot.com',
    iosClientId: '298093404093-qtn7krkrfofe0o34m5ukcbtp51bge82a.apps.googleusercontent.com',
    iosBundleId: 'ife.com.mynotes.RunnerTests',
  );
}
